{{- if .Values.query_frontend.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cortex.queryFrontendFullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cortex.queryFrontendLabels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.query_frontend.annotations | nindent 4 }}
spec:
  replicas: {{ .Values.query_frontend.replicas }}
  selector:
    matchLabels:
      {{- include "cortex.queryFrontendSelectorLabels" . | nindent 6 }}
  strategy:
    {{- toYaml .Values.query_frontend.strategy | nindent 4 }}
  template:
    metadata:
      labels:
        {{- include "cortex.queryFrontendLabels" . | nindent 8 }}
        {{- with .Values.query_frontend.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      annotations:
        checksum/config: {{ include "cortex.configChecksum" . }}
      {{- with .Values.query_frontend.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      serviceAccountName: {{ .Values.query_frontend.serviceAccount.name | default (include "cortex.serviceAccountName" . ) }}
      {{- if .Values.query_frontend.priorityClassName }}
      priorityClassName: {{ .Values.query_frontend.priorityClassName }}
      {{- end }}
      {{- if .Values.query_frontend.securityContext.enabled }}
      securityContext: {{- omit .Values.query_frontend.securityContext "enabled" | toYaml | nindent 8 }}
      {{- end }}
      initContainers:
        {{- toYaml .Values.query_frontend.initContainers | nindent 8 }}
      {{- if .Values.image.pullSecrets }}
      imagePullSecrets:
      {{- range .Values.image.pullSecrets }}
        - name: {{ . }}
      {{- end }}
      {{- end }}
      containers:
        - name: query-frontend
          image: "{{ .Values.image.repository }}:{{ default .Chart.AppVersion .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - "-target=query-frontend"
            - "-config.file=/etc/cortex/cortex.yaml"
            {{- include "cortex.frontend-memcached" . | nindent 12 }}
          {{- range $key, $value := .Values.query_frontend.extraArgs }}
            - "-{{ $key }}={{ $value }}"
          {{- end }}
          volumeMounts:
            {{- if .Values.query_frontend.extraVolumeMounts }}
            {{- toYaml .Values.query_frontend.extraVolumeMounts | nindent 12}}
            {{- end }}
            - name: config
              mountPath: /etc/cortex
            - name: runtime-config
              mountPath: /etc/cortex-runtime-config
          ports:
            - name: http-metrics
              containerPort: {{ .Values.config.server.http_listen_port }}
              protocol: TCP
            - name: grpc
              containerPort: {{ .Values.config.server.grpc_listen_port }}
              protocol: TCP
          startupProbe:
            {{- toYaml .Values.query_frontend.startupProbe | nindent 12 }}
          livenessProbe:
            {{- toYaml .Values.query_frontend.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.query_frontend.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.query_frontend.resources | nindent 12 }}
          {{- if .Values.query_frontend.containerSecurityContext.enabled }}
          securityContext: {{- omit .Values.query_frontend.containerSecurityContext "enabled" | toYaml | nindent 12 }}
          {{- end }}
          {{- if .Values.query_frontend.env }}
          env:
            {{- toYaml .Values.query_frontend.env | nindent 12 }}
          {{- end }}
          {{- with .Values.query_frontend.lifecycle }}
          lifecycle:
            {{- toYaml . | nindent 12 }}
          {{- end }}
        {{- if .Values.query_frontend.extraContainers }}
        {{- toYaml .Values.query_frontend.extraContainers | nindent 8}}
        {{- end }}
      nodeSelector:
        {{- toYaml .Values.query_frontend.nodeSelector | nindent 8 }}
      affinity:
        {{- toYaml .Values.query_frontend.affinity | nindent 8 }}
      tolerations:
        {{- toYaml .Values.query_frontend.tolerations | nindent 8 }}
      terminationGracePeriodSeconds: {{ .Values.query_frontend.terminationGracePeriodSeconds }}
      volumes:
        {{- include "cortex.configVolume" . | nindent 8 }}
        - name: runtime-config
          configMap:
            name: {{ template "cortex.fullname" . }}-runtime-config
        {{- if .Values.query_frontend.extraVolumes }}
        {{- toYaml .Values.query_frontend.extraVolumes | nindent 8}}
        {{- end }}
{{- end -}}