apiVersion: v1
kind: Service
metadata:
  name: {{ include "cortex.ingesterFullname" . }}-headless
  labels:
    {{- include "cortex.ingesterLabels" . | nindent 4 }}
    {{- with .Values.ingester.service.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- toYaml .Values.ingester.service.annotations | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: {{ .Values.config.server.http_listen_port }}
      protocol: TCP
      name: http-metrics
      targetPort: http-metrics
  selector:
    {{- include "cortex.ingesterSelectorLabels" . | nindent 4 }}
