{{- if .Values.overrides_exporter.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cortex.overridesExporterFullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cortex.overridesExporterLabels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.overrides_exporter.annotations | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "cortex.overridesExporterSelectorLabels" . | nindent 6 }}
  strategy:
    {{- toYaml .Values.overrides_exporter.strategy | nindent 4 }}
  template:
    metadata:
      labels:
        {{- include "cortex.overridesExporterLabels" . | nindent 8 }}
        {{- with .Values.overrides_exporter.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      annotations:
      {{- if .Values.useExternalConfig }}
        checksum/config: {{ .Values.externalConfigVersion }}
      {{- else }}
        checksum/config: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
      {{- end }}
      {{- with .Values.overrides_exporter.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      serviceAccountName: {{ template "cortex.serviceAccountName" . }}
      {{- if .Values.overrides_exporter.priorityClassName }}
      priorityClassName: {{ .Values.overrides_exporter.priorityClassName }}
      {{- end }}
      {{- if .Values.overrides_exporter.securityContext.enabled }}
      securityContext: {{- omit .Values.overrides_exporter.securityContext "enabled" | toYaml | nindent 8 }}
      {{- end }}
      initContainers:
        {{- toYaml .Values.overrides_exporter.initContainers | nindent 8 }}
      {{- if .Values.image.pullSecrets }}
      imagePullSecrets:
      {{- range .Values.image.pullSecrets }}
        - name: {{ . }}
      {{- end }}
      {{- end }}
      containers:
        - name: overrides-exporter
          image: "{{ .Values.image.repository }}:{{ default .Chart.AppVersion .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - "-target=overrides-exporter"
            - "-config.file=/etc/cortex/cortex.yaml"
          {{- range $key, $value := .Values.overrides_exporter.extraArgs }}
            - "-{{ $key }}={{ $value }}"
          {{- end }}
          volumeMounts:
            {{- if .Values.overrides_exporter.extraVolumeMounts }}
            {{- toYaml .Values.overrides_exporter.extraVolumeMounts | nindent 12 }}
            {{- end }}
            - name: config
              mountPath: /etc/cortex
            - name: runtime-config
              mountPath: /etc/cortex-runtime-config
          ports:
            - name: http-metrics
              containerPort: {{ .Values.config.server.http_listen_port }}
              protocol: TCP
          startupProbe:
            {{- toYaml .Values.overrides_exporter.startupProbe | nindent 12 }}
          livenessProbe:
            {{- toYaml .Values.overrides_exporter.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.overrides_exporter.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.overrides_exporter.resources | nindent 12 }}
          {{- if .Values.overrides_exporter.containerSecurityContext.enabled }}
          securityContext: {{- omit .Values.overrides_exporter.containerSecurityContext "enabled" | toYaml | nindent 12 }}
          {{- end }}
          {{- if .Values.overrides_exporter.env }}
          env:
            {{- toYaml .Values.overrides_exporter.env | nindent 12 }}
          {{- end }}
          {{- with .Values.overrides_exporter.lifecycle }}
          lifecycle:
            {{- toYaml . | nindent 12 }}
          {{- end }}
        {{- if .Values.overrides_exporter.extraContainers }}
        {{- toYaml .Values.overrides_exporter.extraContainers | nindent 8 }}
        {{- end }}
      nodeSelector:
        {{- toYaml .Values.overrides_exporter.nodeSelector | nindent 8 }}
      {{- if .Values.overrides_exporter.topologySpreadConstraints }}
      topologySpreadConstraints:
      {{- toYaml .Values.overrides_exporter.topologySpreadConstraints | nindent 8}}
      {{- end }}
      affinity:
        {{- toYaml .Values.overrides_exporter.affinity | nindent 8 }}
      tolerations:
        {{- toYaml .Values.overrides_exporter.tolerations | nindent 8 }}
      terminationGracePeriodSeconds: {{ .Values.overrides_exporter.terminationGracePeriodSeconds }}
      volumes:
        {{- include "cortex.configVolume" . | nindent 8 }}
        - name: runtime-config
          configMap:
            name: {{ template "cortex.fullname" . }}-runtime-config
        {{- if .Values.overrides_exporter.extraVolumes }}
        {{- toYaml .Values.overrides_exporter.extraVolumes | nindent 8 }}
        {{- end }}
{{- end }}
