{{- if .Values.nginx.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "cortex.nginxFullname" . }}
  labels:
    {{- include "cortex.nginxLabels" . | nindent 4 }}
    {{- with .Values.nginx.service.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- toYaml .Values.nginx.service.annotations | nindent 4 }}
spec:
  type: {{ .Values.nginx.service.type }}
  ports:
    - port: {{ .Values.nginx.http_listen_port }}
      protocol: TCP
      name: http-metrics
      targetPort: http-metrics
  selector:
    {{- include "cortex.nginxSelectorLabels" . | nindent 4 }}
{{- end }}
