apiVersion: v1
kind: Service
metadata:
  name: {{ include "cortex.fullname" . }}-memberlist
  labels:
    {{- include "cortex.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: {{ .Values.config.memberlist.bind_port }}
      protocol: TCP
      name: grpc
      targetPort: grpc
  selector:
    {{- include "cortex.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/part-of: memberlist
