apiVersion: v1
kind: Service
metadata:
  name: {{ include "cortex.distributorFullname" . }}
  labels:
    {{- include "cortex.distributorLabels" . | nindent 4 }}
    {{- with .Values.distributor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- toYaml .Values.distributor.annotations | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
    - port: {{ .Values.config.server.http_listen_port }}
      protocol: TCP
      name: http-metrics
      targetPort: http-metrics
    - port: {{ .Values.config.server.grpc_listen_port }}
      protocol: TCP
      name: grpc
      targetPort: grpc
  selector:
    {{- include "cortex.distributorSelectorLabels" . | nindent 4 }}
