{{- if ne .Values.config.storage.engine "blocks" -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cortex.tableManagerFullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cortex.tableManagerLabels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.table_manager.annotations | nindent 4 }}
spec:
  replicas: {{ .Values.table_manager.replicas }}
  selector:
    matchLabels:
      {{- include "cortex.tableManagerSelectorLabels" . | nindent 6 }}
  strategy:
    {{- toYaml .Values.table_manager.strategy | nindent 4 }}
  template:
    metadata:
      labels:
        {{- include "cortex.tableManagerLabels" . | nindent 8 }}
        {{- with .Values.table_manager.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      annotations:
        checksum/config: {{ include "cortex.configChecksum" . }}
        {{- with .Values.table_manager.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      serviceAccountName: {{ .Values.table_manager.serviceAccount.name | default (include "cortex.serviceAccountName" . ) }}
      {{- if .Values.table_manager.priorityClassName }}
      priorityClassName: {{ .Values.table_manager.priorityClassName }}
      {{- end }}
      {{- if .Values.table_manager.securityContext.enabled }}
      securityContext: {{- omit .Values.table_manager.securityContext "enabled" | toYaml | nindent 8 }}
      {{- end }}
      initContainers:
        {{- toYaml .Values.table_manager.initContainers | nindent 8 }}
      {{- if .Values.image.pullSecrets }}
      imagePullSecrets:
      {{- range .Values.image.pullSecrets }}
        - name: {{ . }}
      {{- end }}
      {{- end }}
      containers:
        - name: table-manager
          image: "{{ .Values.image.repository }}:{{ default .Chart.AppVersion .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - "-target=table-manager"
            - "-config.file=/etc/cortex/cortex.yaml"
          {{- if .Values.purger.enabled }}
            - "-purger.enable"
          {{- end }}
          {{- range $key, $value := .Values.table_manager.extraArgs }}
            - "-{{ $key }}={{ $value }}"
          {{- end }}
          volumeMounts:
            {{- if .Values.table_manager.extraVolumeMounts }}
            {{- toYaml .Values.table_manager.extraVolumeMounts | nindent 12}}
            {{- end }}
            - name: config
              mountPath: /etc/cortex
            - name: runtime-config
              mountPath: /etc/cortex-runtime-config
            - name: storage
              mountPath: "/data"
              subPath: {{ .Values.table_manager.persistentVolume.subPath }}
          ports:
            - name: http-metrics
              containerPort: {{ .Values.config.server.http_listen_port }}
              protocol: TCP
          startupProbe:
            {{- toYaml .Values.table_manager.startupProbe | nindent 12 }}
          livenessProbe:
            {{- toYaml .Values.table_manager.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.table_manager.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.table_manager.resources | nindent 12 }}
          {{- if .Values.table_manager.containerSecurityContext.enabled }}
          securityContext: {{- omit .Values.table_manager.containerSecurityContext "enabled" | toYaml | nindent 12 }}
          {{- end }}
          {{- if .Values.table_manager.env }}
          env:
            {{- toYaml .Values.table_manager.env | nindent 12 }}
          {{- end }}
        {{- if .Values.table_manager.extraContainers }}
        {{- toYaml .Values.table_manager.extraContainers | nindent 8}}
        {{- end }}
      nodeSelector:
        {{- toYaml .Values.table_manager.nodeSelector | nindent 8 }}
      {{- if .Values.table_manager.topologySpreadConstraints }}
      topologySpreadConstraints:
      {{- toYaml .Values.table_manager.topologySpreadConstraints | nindent 8}}
      {{- end }}
      affinity:
        {{- toYaml .Values.table_manager.affinity | nindent 8 }}
      tolerations:
        {{- toYaml .Values.table_manager.tolerations | nindent 8 }}
      terminationGracePeriodSeconds: {{ .Values.table_manager.terminationGracePeriodSeconds }}
      volumes:
        {{- include "cortex.configVolume" . | nindent 8 }}
        - name: runtime-config
          configMap:
            name: {{ template "cortex.fullname" . }}-runtime-config
        - name: storage
          emptyDir: {}
        {{- if .Values.table_manager.extraVolumes }}
        {{- toYaml .Values.table_manager.extraVolumes | nindent 8}}
        {{- end }}
{{- end -}}
