{{- if and (gt (int .Values.querier.replicas) 1) (.Values.querier.podDisruptionBudget) }}
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ include "cortex.querierFullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cortex.querierLabels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "cortex.querierSelectorLabels" . | nindent 6 }}
  {{- toYaml .Values.querier.podDisruptionBudget | nindent 2 }}
{{- end }}
