name: Validate renovate config

on:
  push:
    paths:
      - renovate.json
      - .github/workflows/renovate-config-validator.yml

jobs:
  validate:
    name: validate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Validate
        run: npx --yes --package renovate -- renovate-config-validator
